# docker-compose.yml
version: '3.8'

services:
  data_service:
    build:
      context: ./data-microservice # Caminho para o Dockerfile (ou diretório com package.json se usar imagem base Node)
      dockerfile: Dockerfile # Vamos criar este Dockerfile
    container_name: data_service_container
    restart: unless-stopped
    expose:
      - "3001" # Expõe a porta internamente para a rede do Docker
    networks:
      - app_network

  nginx_proxy:
    image: nginx:1.25-alpine # Imagem oficial do NGINX
    container_name: nginx_proxy_container
    restart: unless-stopped
    ports:
      - "8080:80" # Mapeia a porta 8080 do host para a porta 80 do container NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mapeia o arquivo de configuração do NGINX
      - nginx_cache_volume:/var/cache/nginx # Volume para persistir o cache do NGINX
    depends_on:
      - data_service # Garante que o microsserviço inicie antes do NGINX
    networks:
      - app_network
    # Adiciona healthcheck para o NGINX (opcional, mas bom)
    healthcheck:
      test: ["CMD", "service", "nginx", "status"] # Ou um curl para um endpoint do NGINX
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  nginx_cache_volume: # Define um volume nomeado para o cache do NGINX
